import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

import { Footer } from "@/components";
import { Navbar } from "@/components/UI/Navbar";
import { twMerge } from "tailwind-merge";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="h-full">
			<body
				className={twMerge([
					manrope.className,
					"overflow-x-hidden flex flex-col h-full",
				])}
			>
				<Navbar />
				<div className="grow">{children}</div>
				<Footer />
			</body>
		</html>
	);
}
